PLATFORM_CFLAGS = -m32
PLATFORM_EXT = .dll
RC_FILE = mbandcomp.rc
RES_FILE = mbandcomp.res

WINDRES = windres
WINDRES_FLAGS = -O coff -F pe-i386

include generic.mk

$(RES_FILE): $(RC_FILE)
	$(WINDRES) $(WINDRES_FLAGS) $(RC_FILE) -o $(RES_FILE)
